os:
  - linux

services:
  - docker

env:
  - GAME_NAME="KAG Rewritten" GODOT_VERSION="3.2"

install:
- docker pull "barichello/godot-ci:${GODOT_VERSION}"

script:
# Desktop
- docker run -v "$(pwd)" "barichello/godot-ci:${GODOT_VERSION}" /bin/bash -c "godot --export 'Windows Desktop' $(pwd)/build/windows/${GAME_NAME}.exe"
- docker run -v "$(pwd)" "barichello/godot-ci:${GODOT_VERSION}" /bin/bash -c "godot --export 'Linux/X11' $(pwd)/build/linux/${GAME_NAME}"
- docker run -v "$(pwd)" "barichello/godot-ci:${GODOT_VERSION}" /bin/bash -c "godot --export 'Mac OSX' $(pwd)/build/mac/${GAME_NAME}-mac.zip"
# Web
- docker run -v "$(pwd)" "barichello/godot-ci:${GODOT_VERSION}" /bin/bash -c "godot --export 'HTML5' $(pwd)/build/html5/index.html"

before_deploy:
- zip -j "${GAME_NAME}-linux.zip"   build/linux/*
- zip -j "${GAME_NAME}-windows.zip" build/windows/*
- cp -R build/mac/* . # already a zip

deploy:
- provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN
  file:
    - "${GAME_NAME}-linux.zip"
    - "${GAME_NAME}-windows.zip"
    - "${GAME_NAME}-mac.zip"
  on:
    all_branches: true
    tags: true

- provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build/html5
  on:
    branch: master
    # tags: true
