os:
  - linux

env:
  - GAME_NAME="KAG Rewritten" GODOT_VERSION="3.2"

install:
- wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip \
- wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz \
- mkdir ~/.cache \
- mkdir -p ~/.config/godot \
- mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION}.stable \
- unzip Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip \
- mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 /usr/local/bin/godot \
- unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz \
- mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}.stable \
- rm -f Godot_v${GODOT_VERSION}-stable_export_templates.tpz Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip

script:
# Desktop
- godot --export "Windows Desktop" build/windows/${GAME_NAME}.exe
- godot --export "Linux/X11" build/linux/${GAME_NAME}
- godot --export "Mac OSX" build/mac/${GAME_NAME}-mac.zip
# Web
- godot --export "HTML5" build/html5/index.html

before_deploy:
- zip -j "${GAME_NAME}-linux.zip"   ./build/linux/*
- zip -j "${GAME_NAME}-windows.zip" ./build/windows/*
- cp -R ./build/mac/* . # already a zip

deploy:
- provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN
  file:
    - "${GAME_NAME}-linux.zip"
    - "${GAME_NAME}-windows.zip"
    - "${GAME_NAME}-mac.zip"
  on:
    all_branches: true
    tags: true

- provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build/html5
  on:
    branch: master
    # tags: true
