env:
  - GAME_NAME="KAG Rewritten"

install:
- wget "https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_linux_headless.64.zip"
- unzip "./Godot_v3.2-stable_linux_headless.64.zip"
- mv "./Godot_v3.2-stable_linux_headless.64" godot

script:
- godot --path ./ --export "Windows Desktop" output/linux/${GAME_NAME}.exe
- godot --path ./ --export "Mac OSX" output/mac/${GAME_NAME}-mac.zip
- godot --path ./ --export "Linux/X11" output/windows/${GAME_NAME}
- godot --path ./ --export "HTML5" output/html5/index.html

before_deploy:
- zip -j "${GAME_NAME}-linux.zip"   output/linux/*
- zip -j "${GAME_NAME}-windows.zip" output/windows/*
- cp -R output/mac/* . # already a zip

deploy:
- provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - "${GAME_NAME}-linux.zip"
    - "${GAME_NAME}-windows.zip"
    - "${GAME_NAME}-mac.zip"
  on:
    all_branches: true
    tags: true

- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: output/html5
  on:
    branch: master
    # tags: true
