language: minimal

git:
  quiet: true

os: linux

env: GAME_NAME="KAG Rewritten" GODOT_VERSION="3.2"

install:
- wget -q "https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip"
- wget -q "https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
- mkdir -p ~/.cache
- mkdir -p ~/.config/godot
- mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION}.stable
- unzip Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
- unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
- sudo mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 /usr/local/bin/godot
- mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}.stable

script:
- mkdir -p "build/windows"
- mkdir -p "build/linux"
- mkdir -p "build/mac"
- mkdir -p "build/html5"
# Desktop
- godot --export "Windows Desktop" "build/windows/${GAME_NAME}.exe"
- godot --export "Linux/X11" "build/linux/${GAME_NAME}"
- godot --export "Mac OSX" "build/mac/${GAME_NAME}-mac.zip"
# Web
- godot --export "HTML5" "build/html5/index.html"

before_deploy:
- zip -r "${GAME_NAME}-linux.zip" build/linux/*
- zip -r "${GAME_NAME}-windows.zip" build/windows/*
# Only copying needed, exporting for Mac outputs a zip
- cp -R build/mac/* .

deploy:
- provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN
  file:
    - "${GAME_NAME}-linux.zip"
    - "${GAME_NAME}-windows.zip"
    - "${GAME_NAME}-mac.zip"
  on:
    all_branches: true
    tags: true

- provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build/html5
  on:
    branch: master
#   tags: true
