os:
  - linux

env:
  - GAME_NAME="KAG Rewritten"

install:
- wget "https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_linux_headless.64.zip"
- wget "https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_export_templates.tpz"
- unzip "./Godot_v3.2-stable_linux_headless.64.zip"
- unzip "./Godot_v3.2-stable_export_templates.tpz"
- mv "./Godot_v3.2-stable_linux_headless.64" godot

script:
# Desktop
- ./godot --path . --export "./templates/windows_64_release.exe" output/linux/${GAME_NAME}.exe
- ./godot --path . --export "./templates/linux_x11_64_release" output/windows/${GAME_NAME}
- ./godot --path . --export "./templates/osx.zip" output/mac/${GAME_NAME}-mac.zip
# Web
- ./godot --path . --export "./templates/webassembly_release.zip" output/html5/index.html

before_deploy:
- zip -j "${GAME_NAME}-linux.zip"   output/linux/*
- zip -j "${GAME_NAME}-windows.zip" output/windows/*
- cp -R output/mac/* . # already a zip

deploy:
- provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN
  file:
    - "${GAME_NAME}-linux.zip"
    - "${GAME_NAME}-windows.zip"
    - "${GAME_NAME}-mac.zip"
  on:
    all_branches: true
    tags: true

- provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: output/html5
  on:
    branch: master
    # tags: true
