language: minimal

git:
  quiet: true

os: linux

env: GAME_NAME="KAG Rewritten" GODOT_VERSION="3.2"

install:
- wget -q "https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip"
- wget -q "https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
- mkdir -p ~/.cache
- mkdir -p ~/.config/godot
- mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION}.stable
- unzip Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
- unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
- sudo mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 /usr/local/bin/godot
- mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}.stable

script:
- mkdir -p "build/windows"
- mkdir -p "build/linux"
- mkdir -p "build/mac"
- mkdir -p "build/html5"
# Desktop
- godot --export "Windows Desktop" "build/windows/${GAME_NAME}.exe"
- godot --export "Linux/X11" "build/linux/${GAME_NAME}"
- godot --export "Mac OSX" "build/mac/${GAME_NAME}-mac.zip"
# Web
- godot --export "HTML5" "build/html5/index.html"

before_deploy:
# Only copying needed, exporting for Mac outputs a zip
- cp -R build/mac/* .
- zip -jr "${GAME_NAME}-linux.zip" build/linux
- zip -jr "${GAME_NAME}-windows.zip" build/windows
- zip -jr "${GAME_NAME}-html.zip" build/html5

deploy:
- provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN
  file:
    - "${GAME_NAME}-mac.zip"
    - "${GAME_NAME}-linux.zip"
    - "${GAME_NAME}-windows.zip"
    - "${GAME_NAME}-html.zip"
  on:
    all_branches: true
    tags: true

- provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build/html5
  on:
    branch: master
#   tags: true

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
